#!/bin/bash
ls -al

# Change directory to the parent directory of the working directory
cd ..

# List files in the parent directory
ls -al

# Change directory to /boot
cd /boot

# List files in the /boot directory
ls -al
